language: bash
services: docker

cache:
  directories:
   - /home/travis/.cache/pip/

script:
  - set -e
  - wget -qO- https://api.wodby.com/api/v1/get/cli | sh
  - wodby ci init "${WODBY_INSTANCE_UUID}"

  - >
    wodby ci run -v $HOME/.cache/pip:/home/wodby/.cache/pip -i wodby/python:3.6 -- \
      sh -c "pip install mkdocs-material markdown-include && mkdocs build"

  - wodby ci build --from ./site --to /var/www/html/docs
  - wodby ci release
  - wodby ci deploy

  - >
    docker run --rm -it -e VARNISH_SECRET="${VARNISH_SECRET}" -v "${PWD}"/purge-cache.sh:/opt/purge-cache.sh \
      wodby/drupal-varnish:4.1-2.5.0 bash /opt/purge-cache.sh