language: bash
services: docker

cache:
  directories:
   - /home/travis/.cache/pip/

script:
  - set -e
  - wget -qO- https://api.wodby.com/api/v1/get/cli | sh
  - wodby ci init "${WODBY_INSTANCE_UUID}"

  - wodby ci run -v $HOME/.cache/pip:$HOME/.cache/pip -i wodby/python:3.6 -- pip install mkdocs-material markdown-include
  - wodby ci run -i wodby/python:3.6 -- mkdocs build

  - wodby ci build --from ./site
  - wodby ci release
  - wodby ci deploy
