box: billryan/gitbook:base

build:
    steps:
        - script:
            name: build
            code: |
                gitbook install
                gitbook build

push:
    box: nginx:alpine
    steps:
        - script:
            name: install dependencies
            code: |
                apk add --update curl bash
        - script:
            name: mv static files
            code: |
                rm -rf /usr/share/nginx/html/*
                mv $WERCKER_SOURCE_DIR/_book/* /usr/share/nginx/html
        - internal/docker-push:
            registry: https://registry.hub.docker.com
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
            repository: wodby/docs
            tag: latest, $WERCKER_GIT_BRANCH

deployment:
    steps:
        - script:
            name: deployment
            code: |
                curl -sS \
                        -H "Content-type: application/json" \
                        -H "Authorization: token ${WODBY_API_TOKEN}" \
                        -X POST https://api.wodby.com/api/v2/bundles/deploy?org_id="${WODBY_ORG_UUID}"\&service_image=wodby/docs:"${WERCKER_GIT_BRANCH}"\&cause="${WERCKER_GIT_COMMIT}"
