site_name: Wodby 2.0 documentation
site_description: Wodby 2.0 documentation
site_author: Wodby, Inc.
site_url: https://wodby.com/docs/2.0

repo_name: wodby/docs
repo_url: https://github.com/wodby/docs

copyright: Wodby, Inc.

extra:
  social:
    - type: globe
      link: https://wodby.com
    - type: github-alt
      link: https://github.com/wodby
    - type: twitter
      link: https://twitter.com/wodbycloud

google_analytics:
  - 'UA-61873765-1'
  - 'auto'

theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: 'indigo'
    accent: 'indigo'
  custom_dir: 'theme'

extra_css: ["assets/wodby.css"]
extra_javascript: ["assets/jquery-3.3.1.min.js", "assets/intercom.js", "assets/wodby.js"]

markdown_extensions:
  - codehilite
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_include.include:
      base_path: includes

nav:
  - Home: index.md
  - Open Source: oss.md
  - Status: status.md
  - Support: support.md
  - Apps:
    - New app: apps/new.md
    - Instances: apps/instances.md
  - Clusters:
    - Overview: clusters/index.md
    - New cluster: clusters/new.md
  - Stacks:
    - Overview: stacks/index.md
  - Services:
    - Overview: services/index.md
  - Integrations:
    - Overview: integrations/index.md
    - GCP: integrations/gcp.md
